kind: Service
apiVersion: v1
metadata:
  name: apache-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80 
      nodePort: 32312
    - name: https
      port: 8081
      targetPort: 80
      nodePort: 32313
  selector:
    app: abcd
  type: LoadBalancer
